// This file is automatically generated. Do not edit it directly.
import { createClient, SupabaseClient } from "@supabase/supabase-js";

const SUPABASE_URL =
  import.meta.env.VITE_SUPABASE_URL ||
  "https://ponxumxwjodpgwhepwxc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ||
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBvbnh1bXh3am9kcGd3aGVwd3hjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU0NTE4NTIsImV4cCI6MjA3MTAyNzg1Mn0.J43LGwbU8tQ8_xe3ua4ddb-HTFLsWXoR7R1MVIS3SdE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Detectar modo privado no Safari
const isPrivateMode = async (): Promise<boolean> => {
  if (typeof window === 'undefined') return false;
  
  try {
    const testKey = '__private_mode_test__';
    localStorage.setItem(testKey, 'test');
    localStorage.removeItem(testKey);
    return false;
  } catch (e) {
    return true;
  }
};

// Função para criar armazenamento seguro compatível com Safari
const createSafeStorage = () => {
  // Verificar se estamos no navegador
  if (typeof window === 'undefined') {
    return {
      getItem: () => null,
      setItem: () => {},
      removeItem: () => {},
      clear: () => {}
    };
  }

  // Verificar modo privado e disponibilidade do localStorage
  try {
    const testKey = '__storage_test__';
    localStorage.setItem(testKey, 'test');
    localStorage.removeItem(testKey);
    
    // localStorage disponível
    return {
      getItem: (key: string) => localStorage.getItem(key),
      setItem: (key: string, value: string) => localStorage.setItem(key, value),
      removeItem: (key: string) => localStorage.removeItem(key),
      clear: () => localStorage.clear()
    };
  } catch (e) {
    // Tentar sessionStorage como fallback
    try {
      const testKey = '__session_test__';
      sessionStorage.setItem(testKey, 'test');
      sessionStorage.removeItem(testKey);
      
      return {
        getItem: (key: string) => sessionStorage.getItem(key),
        setItem: (key: string, value: string) => sessionStorage.setItem(key, value),
        removeItem: (key: string) => sessionStorage.removeItem(key),
        clear: () => sessionStorage.clear()
      };
    } catch (e2) {
      // Memory storage como último recurso
      const memoryStorage: { [key: string]: string } = {};
      return {
        getItem: (key: string) => memoryStorage[key] || null,
        setItem: (key: string, value: string) => { memoryStorage[key] = value; },
        removeItem: (key: string) => { delete memoryStorage[key]; },
        clear: () => { Object.keys(memoryStorage).forEach(key => delete memoryStorage[key]); }
      };
    }
  }
};

// Singleton pattern para prevenir múltiplas instâncias
let supabaseInstance: SupabaseClient | null = null;

const createSupabaseClient = (): SupabaseClient => {
  if (supabaseInstance) {
    console.log('🔄 Reutilizando instância existente do Supabase');
    return supabaseInstance;
  }

  console.log('🆕 Criando nova instância do Supabase');
  
  // Detectar se estamos em HTTPS
  const isHTTPS = typeof window !== 'undefined' && window.location.protocol === 'https:';
  
  // Configurações padrão do Supabase
  const config = {
    auth: {
      storage: createSafeStorage(),
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: true,
      flowType: "pkce" as const,
    },
    realtime: {
      params: {
        eventsPerSecond: 10,
      },
      // Forçar WSS em produção HTTPS
      transport: isHTTPS ? 'websocket' : undefined,
      // Configurações específicas para WebSocket seguro
      ...(isHTTPS && {
        heartbeatIntervalMs: 30000,
        reconnectAfterMs: (tries: number) => Math.min(tries * 1000, 10000),
        // Forçar uso de WSS substituindo ws:// por wss://
        wsUrl: SUPABASE_URL.replace('https://', 'wss://').replace('http://', 'ws://') + '/realtime/v1/websocket',
      }),
    },
  };

  supabaseInstance = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, config);

  return supabaseInstance;
};

export const supabase = createSupabaseClient();

// Type definitions for database tables (temporary until types.ts is regenerated)
export type Database = {
  public: {
    Tables: {
      [key: string]: {
        Row: Record<string, any>;
        Insert: Record<string, any>;
        Update: Record<string, any>;
      };
    };
    Views: Record<string, any>;
    Functions: Record<string, any>;
    Enums: Record<string, any>;
    CompositeTypes: Record<string, any>;
  };
};
